### ISSUE TITLE
Add-on Log Display Unavailable

### ISSUE THREAD

**Issue by BrettEBowman** [wingrunr21/hassio-xcel-itron-mqtt#23]
Since upgrading to v1.4.1 yesterday, I'm not able to display the log from the HA Add-on Manager. I get an error stating: "Failed to get 513749ae_xcel-itron-mqtt logs, e.callApiRaw is not a function"
![Screenshot 2024-11-07 112302](https://github.com/user-attachments/assets/0b7ed391-b989-4910-aa95-3d570100fee0)

**Comment by wingrunr21** [comment]
https://community.home-assistant.io/t/error-add-on-logs-are-no-longer-displayed-error-message-e-callapiraw-is-not-a-function/791372

**Comment by BrettEBowman** [comment]
> https://community.home-assistant.io/t/error-add-on-logs-are-no-longer-displayed-error-message-e-callapiraw-is-not-a-function/791372

Thanks! I hadn't updated to Core 2024.11.0 yet. Doing that fixed the problem.
